version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=antipodpiska
      - POSTGRES_USER=antipodpiska
      - POSTGRES_PASSWORD=258963
    ports:
     - ${DB_PORT_IN_DOCKER}
  web:
    build: .
    command: python manage.py runserver ${RUN_PORT_IN_DOCKER}
    volumes:
      - .:/code
    ports:
      - ${APP_PORT_IN_DOCKER}
    depends_on:
      - db
    restart: always
  bot:
    build: .
    command: python manage.py run_bot
    volumes:
    - .:/code
    depends_on:
      - db
      - web
