# Generated by Django 3.2.6 on 2021-09-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-createdAt'], 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(db_index=True, max_length=60, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='telegram_id',
            field=models.TextField(blank=True, null=True, verbose_name='User Name/ID'),
        ),
    ]
