# Generated by Django 3.2.6 on 2021-09-03 10:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bot_customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertelegram',
            options={'ordering': ['-registred'], 'verbose_name': 'Аккаунт Телеги', 'verbose_name_plural': 'Аккаунты от Телеги'},
        ),
        migrations.AddField(
            model_name='usertelegram',
            name='registred',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='Зарегестрирован'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usertelegram',
            name='email',
            field=models.EmailField(max_length=60, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='usertelegram',
            name='telegram_id',
            field=models.IntegerField(unique=True, verbose_name='Telega id'),
        ),
    ]
