# Generated by Django 3.2.6 on 2021-09-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_customers', '0002_auto_20210903_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertelegram',
            name='first_name',
            field=models.CharField(max_length=255, null=True, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='usertelegram',
            name='last_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='usertelegram',
            name='phone',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
